name: Update Blog Posts
on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://iceywu.cn/rss.xml"
          max_post_count: 5
          template: "- [$title]($url) · `$date`"
          date_format: "yyyy-mm-dd"
          committer_username: IceyWu
          committer_email: 3128006406@qq.com
